In [1]:
n=[1,2,3]
z=eval('n')
type(n)

list

In [2]:
max(n)

3

In [8]:
import scipy.sparse as sp
import numpy as np
R = sp.dok_matrix((5,5), dtype=np.float32)
for i in [0,2,4]:
    for j in [2,4]:
        R[i,j]=1.
t=R.asformat('csc')
t.toarray()
type(t)

scipy.sparse.csc.csc_matrix

In [9]:
 coo = t.tocoo().astype(np.float32)

In [10]:
type(coo)

scipy.sparse.coo.coo_matrix

In [11]:
coo.toarray()

array([[0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1.]], dtype=float32)

In [3]:

p=6+[1,2,3,4]
p

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [5]:
import tensorflow as tf 
random_tensor = tf.random_uniform([12])
sess=tf.Session()
sess.run(random_tensor)

array([0.8220538 , 0.94728243, 0.62023306, 0.7644192 , 0.102548  ,
       0.6642885 , 0.52315736, 0.9371022 , 0.5029762 , 0.4834119 ,
       0.16545403, 0.4325837 ], dtype=float32)

In [18]:
r0=tf.reshape([[1,23,3],[2,21,2]], [-1,3])
sess.run(r0)

array([[ 1, 23,  3],
       [ 2, 21,  2]])

ERROR! Session/line number was not unique in database. History logging moved to new session 564


In [23]:
print(list(range(4)))

[0, 1, 2, 3]


In [29]:

a=tf.stack([[[1,2],[2,4]]],1)
sess.run(a)

array([[[1, 2]],

       [[2, 4]]])